<?php

namespace AutocompletionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownRepository extends EntityRepository
{
    public function findAjaxTown ($input)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.town')
            ->where('t.town LIKE :town')
                ->setParameter('town', $input.'%')
            ->getQuery();
        return $qb->getResult();

    }
}
